name: zentrocall_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter # Flutter SDK asosiy kutubxonasi

  # UI va ikonka kutubxonalari
  cupertino_icons: ^1.0.8 # iOS uslubidagi ikonlar
  google_fonts: ^6.2.1 # Google Fonts orqali shriftlar
  iconsax_flutter: ^1.0.1 # Iconsax ikonlar to‘plami
  flutter_svg: ^2.2.0 # SVG formatdagi rasmlarni ko‘rsatish

  # State management va util kutubxonalar
  flutter_bloc: ^9.1.1 # BLoC pattern uchun state management
  equatable: ^2.0.7 # Ob'ektlarni solishtirishni osonlashtiradi (BLoC uchun qulay)

  # Xalqaro tillar va lokalizatsiya
  intl: ^0.20.2 # Sana, vaqt va matnlarni lokalizatsiya qilish

  # Foydali util kutubxonalar
  url_launcher: ^6.3.1 # URL, telefon raqam, email ochish uchun
  fluttertoast: ^8.2.12 # Toast xabarlar ko‘rsatish uchun

  # Networking va lokal xotira
  dio: ^5.8.0+1 # HTTP so‘rovlar uchun (API bilan ishlash)
  shared_preferences: ^2.5.3 # Oddiy lokal ma'lumotlarni saqlash (token, sozlamalar va h.k.)

dev_dependencies:
  flutter_test:
    sdk: flutter # Test yozish uchun

  flutter_lints: ^6.0.0 # Kod sifatini tekshiruvchi linterlar
  build_runner: ^2.5.4 # Kod generatsiyasi uchun (masalan, json_serializable)

flutter:
  uses-material-design: true # Material Design vidjetlarini ishlatish
